### ISSUE TITLE
nml2swc Indentation Error

### ISSUE THREAD

**Issue by nguzman313** [nathantspencer/webknossos_toolkit#19]
There was an Tab Error in the else statement of line 94 of nml2swc.py which caused it to run incorrectly. I believe I have fixed the error, since after making the spacing adjustments, the code ran fine. Here is the corrected version:

[nml2swc2.py.zip](https://github.com/nathantspencer/webknossos_toolkit/files/911178/nml2swc2.py.zip)

**Comment by nathantspencer** [comment]
Good catch, thanks! I've adjusted the indentation in 2130720e9a75a31498fe155c9c36ada035fa3cf1, which should fix the error (although admittedly I haven't actually confirmed that this is the case).
